[api]
addr = ":8080"
allowOrigins = ["http://localhost:3000"] # allow frontend to access backend

[db]
addr = "personality-test-db:6379"
# TODO: Add username and password 
pw = "" # no password set
db = 0 # use default db
